### ISSUE TITLE
Identifying device type (VendorID/ProductID)?

### ISSUE THREAD

**Issue by DOCaCola** [Nemirtingas/OpenXinput#1]
First of all, a very nice project 👍 

Is there a way to get the Vendor or Product ID of a connected XInput device? Currently i have several -wireless- PS4 Controllers that emulate a -wired- Xbox 360 controller (with DS4Windows). I also have a real Xbox 360 wireless controller.

For the real Xbox Controller i'd like to write a small utility that allows to turn it off by pressing the guide button. I only want to hook this device, as power management of the PS4 controllers is already handled by DS4Windows. Is there a way to get something like the device id of a selected XInput device to differenciate between a wired and wireless controller?

**Comment by Nemirtingas** [comment]
Hi,
As of now, you can't get the VID/PID in Xinput 1.3 with my library or with the legit one. But you can do it with Xinput1.4.
See https://github.com/Nemirtingas/OpenXinput/blob/d09a91aa7376de353175e484241fd27f47448adc/OpenXinput.h#L432-L435
and XINPUT_BASE_BUS_INFORMATION.

For the guide button, just call XInputGetStateEx (on both legit and mine) and use the mask `#define XINPUT_GAMEPAD_GUIDE 0x0400`

**Comment by DOCaCola** [comment]
Thanks for your help. I just tried the example and already found the info i was looking for. The wireless playstation controllers are emulated as wired controllers by DS4Windows. So it is easy to figure out which is the real wireless Microsoft Xbox controller.

For my purposes this is sufficient. Since i currently have up to 6 controllers connected at times, regular XInput wouldn't have been enough. Very nice library.

![Unbenannt](https://user-images.githubusercontent.com/2077396/131499420-c349f8b2-e360-4d25-aab8-d81e4339406f.png)

**Comment by Nemirtingas** [comment]
Nice to hear. Unfortunatly, this library is useless until devs are aware of it and code their games to use more than 4 controllers.
Can I/you close this issue if your problem is solved ?

**Comment by DOCaCola** [comment]
There are games out there that use more than 4 controllers and then fall back to DInput or something similar to handle them. I guess your project here is also not very well known as i stumbled upon it by pure luck when reading some other github issue you commented in. I am sure lots of people would start using this library if they were aware of it.

Just finished implementing the code to turn off the controller and it works nicely. Thank you very much for your help.

**Comment by Nemirtingas** [comment]
Well, as its written everywhere that XInput supports only 4 controllers (even is thats actually false), noone checks if it can handle more and fallback to DInput.
