### ISSUE TITLE
Problem with OpenXinput_1.4 when building as static library

### ISSUE THREAD

**Issue by BlacksmithSouls** [Nemirtingas/OpenXinput#11]
Hello, I have a problem when trying to build version 1.4 without BUILD_SHARED_LIBS. It looks like the input is not being processed correctly. Buttons and dpad do not work and the axes are shifted. If you enable BUILD_SHARED_LIBS then everything works correctly. Also in version 1.3 both options work correctly. I took a screenshot showing the problem. The left side with BUILD_SHARED_LIBS enabled, the right side is not. Both sides had the same input.

![1](https://github.com/Nemirtingas/OpenXinput/assets/113226351/726a5c5b-1b30-4d3c-b7af-4116da17e9a7)

**Comment by Nemirtingas** [comment]
Hi,

Thanks for reporting this issue, can you test the latest version of 1.4 ? It seems that the memcpy was totally wrong :)
https://github.com/Nemirtingas/OpenXinput/commit/e72312ff8c401c7cb2b59b665f4266318f1c9d60#diff-e8e84c951e4181dc6d8537d660778515ef6eef54a3ee93feee58818d62de08f7R3750

**Comment by BlacksmithSouls** [comment]
Thanks, now everything works perfectly.
