### ISSUE TITLE
1.3 vs 1.4? Using the .lib vs .dll?

### ISSUE THREAD

**Issue by CollinCodez** [Nemirtingas/OpenXinput#2]
I do have to say, OpenXinput is pretty sweet for allowing you to easily use more than 4 XUSB controllers via XInput. 

I was easily able to make dolphin use more xbox controllers by compiling the XInput 1.4 version to a max controller count of 16 (for 16 player mario kart double dash) and then put the dll in the root folder of the portable dolphin, and it would just work (after compiling dolphin to initialize more controllers).

Now I am working on a Pull Request to Dolphin to get it to officially use OpenXinput where everyone can easily use more controllers. Of course for this use case, they don't just want a straight dll file, they would like the code to be put into dolphin. Is the lib file used pretty much the same as the dll, just rather than being loaded, you have it compiled with everything else?

What are the differences between 1.3 and 1.4?

**Comment by Nemirtingas** [comment]
You can embed the OpenXinput as a static library, I don't think you will get issue with this, you might want to rename functions so it doesn't collide with Xinput.
You might need to export:
namespace XInputCore {
  BOOL WINAPI Initialize();
  BOOL WINAPI Close(bool ContinueHost);
}

And call XInputCore::Initialize(); on application initialize and XInputCore::Close(FALSE); on application exit.


The main difference between 1.3 and 1.4 is that 1.4 legitly allows you to get the device PID/VID and has more functions.
You can use both 1.3 and 1.4 on Windows >= Win7, I don't know about WinXP.

OpenXinput 1.3: # Deprecated on Windows 10, but it still works.
XInputGetDSoundAudioDeviceGuids

OpenXinput 1.4: # Theses will not work on Windows < 10
XInputGetAudioDeviceIds
XInputGetBaseBusInformation
XInputGetCapabilitiesEx

**Comment by Nemirtingas** [comment]
Any new on this ? got an issue with something in OpenXinput ?

**Comment by CollinCodez** [comment]
Not having any issues yet, I have just been busy with college. I will definitely let you know how it goes when I finish up with it!

**Comment by Nemirtingas** [comment]
Ok.
If you need a static library, I could setup a CMake project so you can choose easely between static/shared and configure OpenXinput options like supported controllers count.
