### ISSUE TITLE
compiled xinput1_3.dll and xinput1_4.dll with ini file

### ISSUE THREAD

**Issue by Perseveruz** [Nemirtingas/OpenXinput#8]
Hello, first off, thanks a lot for your opexinput, it is much appreciated. I was wondering if there was a way of using an .ini file along side the openxinput, similar to xinputplus. Reason for asking, is that if I have more than one controller connected to the PC, I would like to specify which controller is to be used, secondly i would like to swap some of the buttons, mainly the shoulder/trigger buttons. I saw the links that you shared with  the already compiled xinput1_3.dll and xinput1_4.dll and would be really great if you could do something similar but with a configurable ini along side the xinput dlls.
Thanks in advance for any help you can provide.

**Comment by Nemirtingas** [comment]
Hi, this project is here to replace the stock XInput library, not to modify its behavior. If I was doing something like you asked, it would break the compatibility with XInput.
This project is opensource and free, people wanting something like that would build their own solution.
This project should stay clean and fully compatible with XInput.

**Comment by Perseveruz** [comment]
thanks for taking the time to respond to my question and fully understand your point. will do some research and see if i can work something out on my own :)
